-- =====================================================================
-- Migration: Phase 1 canonical first-party event stream
-- Run this in the "torah-by-the-table" (external) Supabase SQL editor —
-- the same project reached by getSupabaseAdmin() / EXT_SUPABASE_URL.
--
-- Safe to re-run (idempotent).
--
-- This table is the single canonical behavioral event stream. The legacy
-- page_views / search_events / download_events tables keep working and are
-- still written, because the existing download dashboard reads them.
--
-- No IP addresses and no raw user agents are stored. Device type is derived
-- server-side. Geo is limited to country + region for this table.
-- =====================================================================

create extension if not exists "pgcrypto";

create table if not exists public.analytics_events (
  id uuid primary key default gen_random_uuid(),

  -- Idempotency key generated by the browser; repeated deliveries of the
  -- same logical event (sendBeacon retry, fetch fallback, SW replay) collapse
  -- onto one row.
  event_id text not null,

  event_name text not null,
  occurred_at timestamptz not null default now(),

  -- Identity
  visitor_id text not null,
  session_id text not null,
  is_new_visitor boolean not null default false,

  -- Location in the app
  path text,
  landing_path text,
  source_path text,

  -- Publication context
  publication_id text,
  publication_title text,
  publication_series text,
  publisher text,
  parsha text,
  jewish_year integer,

  -- Environment / attribution (first-touch for the session)
  device_type text,
  referrer_host text,
  referrer_url text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  source_group text,
  country text,
  region text,

  -- Event-specific values (query, result_count, filter values, share method,
  -- active_seconds, error_code, already_subscribed, ...)
  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now()
);

create unique index if not exists analytics_events_event_id_key
  on public.analytics_events (event_id);

create index if not exists analytics_events_occurred_at_idx
  on public.analytics_events (occurred_at desc);
create index if not exists analytics_events_name_time_idx
  on public.analytics_events (event_name, occurred_at desc);
create index if not exists analytics_events_session_idx
  on public.analytics_events (session_id);
create index if not exists analytics_events_visitor_idx
  on public.analytics_events (visitor_id);
create index if not exists analytics_events_publication_idx
  on public.analytics_events (publication_id);
create index if not exists analytics_events_source_group_idx
  on public.analytics_events (source_group);

grant all on public.analytics_events to service_role;

alter table public.analytics_events enable row level security;
-- Reads and writes happen only through the server (service role).
-- No anon/authenticated policies are defined on purpose.
