import { useCallback, useEffect, useState } from "react";
import { adminPhase1Funnel } from "@/integrations/supabase/api.functions";
import { adminPhase1SessionFunnel } from "@/integrations/supabase/phase1-session-funnel";

type FunnelData = Awaited<ReturnType<typeof adminPhase1Funnel>>;
type OkData = Extract<FunnelData, { ok: true }>;
type SessionFunnelData = Awaited<ReturnType<typeof adminPhase1SessionFunnel>>;
const RANGES = [1, 7, 30, 90];
function pct(n:number,d:number){return d?`${Math.round(n/d*1000)/10}%`:"—";}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-accent/40 bg-background/60 p-4"><div className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</div><div className="mt-1 font-serif text-2xl font-bold text-primary">{value}</div></div>}
export default function Phase1Funnel({accessToken}:{accessToken:string}){
 const [days,setDays]=useState(7); const [data,setData]=useState<OkData|null>(null); const [f,setF]=useState<SessionFunnelData["funnel"]|null>(null); const [problem,setProblem]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [publicationScope,setPublicationScope]=useState("Rosh Hashanah");
 const load=useCallback(async()=>{if(!accessToken)return;setLoading(true);setProblem(null);try{const [r,s]=await Promise.all([adminPhase1Funnel({data:{accessToken,days}}),adminPhase1SessionFunnel({data:{accessToken,days}})]);if(r.ok){setData(r);setF(s.funnel)}else{setData(null);setF(null);setProblem(r.reason)}}catch(e){setData(null);setF(null);setProblem(e instanceof Error?e.message:"Could not load analytics.")}finally{setLoading(false)}},[accessToken,days]);
 useEffect(()=>{void load()},[load]);
 const parshas=data?Array.from(new Set(data.publications.map(p=>p.parsha).filter((p):p is string=>Boolean(p)))):[]; const selected=publicationScope==="all"?null:publicationScope; const pubs=data?(selected?data.publications.filter(p=>p.parsha===selected):data.publications):[];
 return <div><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-serif text-2xl font-bold text-primary">Visitor Funnel</h2><div className="flex items-center gap-2">{RANGES.map(d=><button key={d} type="button" onClick={()=>setDays(d)} className={`rounded-full border px-3 py-1 text-xs font-semibold ${days===d?"border-accent bg-accent text-accent-foreground":"border-accent/40 text-primary"}`}>{d}d</button>)}<button type="button" onClick={()=>void load()} className="rounded-full border border-accent/40 px-3 py-1 text-xs font-semibold text-primary">Refresh</button></div></div>
 {loading&&<p className="mt-3 text-sm text-muted-foreground">Loading…</p>}{problem&&<p className="mt-3 text-sm text-muted-foreground">No funnel data available yet ({problem}).</p>}
 {data&&<><div className="mt-4 grid gap-3 grid-cols-2 lg:grid-cols-4"><Card label="Unique visitors" value={String(data.totals.uniqueVisitors)}/><Card label="Engaged visitors" value={String(f?.engagedVisitors??0)}/><Card label="Engaged sessions" value={String(f?.engagedSessions??0)}/><Card label="Low-confidence sessions" value={String(f?.lowConfidenceSessions??0)}/><Card label="Sessions" value={String(data.totals.sessions)}/><Card label="Returning visitors" value={String(f?.returningVisitors??data.totals.returningVisitors)}/><Card label="PDF accesses" value={String(data.totals.pdfAccesses)}/><Card label="Downloads" value={String(data.totals.downloads)}/></div>
 <p className="mt-3 text-xs text-muted-foreground">Engaged = positive interaction, heartbeat, 2+ page views, or at least 10 seconds of tracked activity. Low-confidence = under 10 seconds, no heartbeat or positive action, and at most one page view. Raw traffic is retained.</p>
 {f&&<div className="mt-6"><h3 className="font-serif text-lg font-bold text-primary">Path to download</h3><div className="mt-2 space-y-1 text-sm">{[{label:"Sessions",value:f.sessions,prev:null as number|null},{label:"Sessions that saw a publication",value:f.impressions,prev:f.sessions},{label:"Sessions that clicked a publication",value:f.clicks,prev:f.impressions},{label:"Sessions that accessed a PDF",value:f.accesses,prev:f.clicks},{label:"Sessions that downloaded",value:f.downloads,prev:f.accesses}].map(x=><div key={x.label} className="flex items-center justify-between rounded-lg border border-accent/25 bg-background/50 px-3 py-2"><span className="font-medium text-primary">{x.label}</span><span className="text-muted-foreground">{x.value}{x.prev!==null&&<> · {pct(x.value,x.prev)}</>}</span></div>)}</div></div>}
 <div className="mt-6"><h3 className="font-serif text-lg font-bold text-primary">Publication performance</h3>{parshas.length>0&&<label className="mt-3 flex w-full flex-col gap-1 text-sm font-medium text-primary sm:max-w-xs"><span>Show collection</span><select value={publicationScope} onChange={e=>setPublicationScope(e.target.value)} className="w-full rounded-lg border border-accent/40 bg-background px-3 py-2 text-base text-primary"><option value="all">All collections</option>{parshas.map(p=><option key={p} value={p}>{p}</option>)}</select></label>}{pubs.length===0?<p className="mt-3 text-sm text-muted-foreground">No publication data yet for {selected??"this range"}.</p>:<div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase tracking-wide text-muted-foreground"><th className="py-2 pr-3">Publication</th><th>Impressions</th><th>Clicks</th><th>PDF accesses</th><th>Downloads</th></tr></thead><tbody>{pubs.map(p=><tr key={p.id} className="border-t border-accent/20"><td className="py-2 pr-3 font-medium text-primary">{p.title}</td><td>{p.impressions}</td><td>{p.clicks}</td><td>{p.accesses}</td><td>{p.downloads}</td></tr>)}</tbody></table></div>}</div></>}
 </div>;
}
