/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShortVortsRouteImport } from './routes/short-vorts'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnsubscribeIndexRouteImport } from './routes/unsubscribe.index'
import { Route as ViewIdRouteImport } from './routes/view.$id'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'
import { Route as OgImageDotpngRouteImport } from './routes/og.image[.]png'
import { Route as ApiTrackViewRouteImport } from './routes/api/track-view'
import { Route as ApiTrackSearchRouteImport } from './routes/api/track-search'
import { Route as ApiTrackDownloadRouteImport } from './routes/api/track-download'
import { Route as ViewIdPdfRouteImport } from './routes/view.$id.pdf'
import { Route as ViewIdDownloadRouteImport } from './routes/view.$id.download'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortVortsRoute = ShortVortsRouteImport.update({
  id: '/short-vorts',
  path: '/short-vorts',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeIndexRoute = UnsubscribeIndexRouteImport.update({
  id: '/unsubscribe/',
  path: '/unsubscribe/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIdRoute = ViewIdRouteImport.update({
  id: '/view/$id',
  path: '/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OgImageDotpngRoute = OgImageDotpngRouteImport.update({
  id: '/og/image.png',
  path: '/og/image.png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackViewRoute = ApiTrackViewRouteImport.update({
  id: '/api/track-view',
  path: '/api/track-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackSearchRoute = ApiTrackSearchRouteImport.update({
  id: '/api/track-search',
  path: '/api/track-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackDownloadRoute = ApiTrackDownloadRouteImport.update({
  id: '/api/track-download',
  path: '/api/track-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIdPdfRoute = ViewIdPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => ViewIdRoute,
} as any)
const ViewIdDownloadRoute = ViewIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ViewIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/mission': typeof MissionRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/short-vorts': typeof ShortVortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/track-download': typeof ApiTrackDownloadRoute
  '/api/track-search': typeof ApiTrackSearchRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/og/image.png': typeof OgImageDotpngRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/view/$id': typeof ViewIdRouteWithChildren
  '/unsubscribe/': typeof UnsubscribeIndexRoute
  '/view/$id/download': typeof ViewIdDownloadRoute
  '/view/$id/pdf': typeof ViewIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/mission': typeof MissionRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/short-vorts': typeof ShortVortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/track-download': typeof ApiTrackDownloadRoute
  '/api/track-search': typeof ApiTrackSearchRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/og/image.png': typeof OgImageDotpngRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/view/$id': typeof ViewIdRouteWithChildren
  '/unsubscribe': typeof UnsubscribeIndexRoute
  '/view/$id/download': typeof ViewIdDownloadRoute
  '/view/$id/pdf': typeof ViewIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/mission': typeof MissionRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/short-vorts': typeof ShortVortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/track-download': typeof ApiTrackDownloadRoute
  '/api/track-search': typeof ApiTrackSearchRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/og/image.png': typeof OgImageDotpngRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/view/$id': typeof ViewIdRouteWithChildren
  '/unsubscribe/': typeof UnsubscribeIndexRoute
  '/view/$id/download': typeof ViewIdDownloadRoute
  '/view/$id/pdf': typeof ViewIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/mission'
    | '/offline'
    | '/privacy'
    | '/robots.txt'
    | '/short-vorts'
    | '/sitemap.xml'
    | '/api/track-download'
    | '/api/track-search'
    | '/api/track-view'
    | '/og/image.png'
    | '/unsubscribe/$token'
    | '/view/$id'
    | '/unsubscribe/'
    | '/view/$id/download'
    | '/view/$id/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/mission'
    | '/offline'
    | '/privacy'
    | '/robots.txt'
    | '/short-vorts'
    | '/sitemap.xml'
    | '/api/track-download'
    | '/api/track-search'
    | '/api/track-view'
    | '/og/image.png'
    | '/unsubscribe/$token'
    | '/view/$id'
    | '/unsubscribe'
    | '/view/$id/download'
    | '/view/$id/pdf'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/mission'
    | '/offline'
    | '/privacy'
    | '/robots.txt'
    | '/short-vorts'
    | '/sitemap.xml'
    | '/api/track-download'
    | '/api/track-search'
    | '/api/track-view'
    | '/og/image.png'
    | '/unsubscribe/$token'
    | '/view/$id'
    | '/unsubscribe/'
    | '/view/$id/download'
    | '/view/$id/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ArchiveRoute: typeof ArchiveRoute
  ContactRoute: typeof ContactRoute
  MissionRoute: typeof MissionRoute
  OfflineRoute: typeof OfflineRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShortVortsRoute: typeof ShortVortsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiTrackDownloadRoute: typeof ApiTrackDownloadRoute
  ApiTrackSearchRoute: typeof ApiTrackSearchRoute
  ApiTrackViewRoute: typeof ApiTrackViewRoute
  OgImageDotpngRoute: typeof OgImageDotpngRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  ViewIdRoute: typeof ViewIdRouteWithChildren
  UnsubscribeIndexRoute: typeof UnsubscribeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-vorts': {
      id: '/short-vorts'
      path: '/short-vorts'
      fullPath: '/short-vorts'
      preLoaderRoute: typeof ShortVortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/': {
      id: '/unsubscribe/'
      path: '/unsubscribe'
      fullPath: '/unsubscribe/'
      preLoaderRoute: typeof UnsubscribeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$id': {
      id: '/view/$id'
      path: '/view/$id'
      fullPath: '/view/$id'
      preLoaderRoute: typeof ViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/image.png': {
      id: '/og/image.png'
      path: '/og/image.png'
      fullPath: '/og/image.png'
      preLoaderRoute: typeof OgImageDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-view': {
      id: '/api/track-view'
      path: '/api/track-view'
      fullPath: '/api/track-view'
      preLoaderRoute: typeof ApiTrackViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-search': {
      id: '/api/track-search'
      path: '/api/track-search'
      fullPath: '/api/track-search'
      preLoaderRoute: typeof ApiTrackSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-download': {
      id: '/api/track-download'
      path: '/api/track-download'
      fullPath: '/api/track-download'
      preLoaderRoute: typeof ApiTrackDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$id/pdf': {
      id: '/view/$id/pdf'
      path: '/pdf'
      fullPath: '/view/$id/pdf'
      preLoaderRoute: typeof ViewIdPdfRouteImport
      parentRoute: typeof ViewIdRoute
    }
    '/view/$id/download': {
      id: '/view/$id/download'
      path: '/download'
      fullPath: '/view/$id/download'
      preLoaderRoute: typeof ViewIdDownloadRouteImport
      parentRoute: typeof ViewIdRoute
    }
  }
}

interface ViewIdRouteChildren {
  ViewIdDownloadRoute: typeof ViewIdDownloadRoute
  ViewIdPdfRoute: typeof ViewIdPdfRoute
}

const ViewIdRouteChildren: ViewIdRouteChildren = {
  ViewIdDownloadRoute: ViewIdDownloadRoute,
  ViewIdPdfRoute: ViewIdPdfRoute,
}

const ViewIdRouteWithChildren =
  ViewIdRoute._addFileChildren(ViewIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ArchiveRoute: ArchiveRoute,
  ContactRoute: ContactRoute,
  MissionRoute: MissionRoute,
  OfflineRoute: OfflineRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShortVortsRoute: ShortVortsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiTrackDownloadRoute: ApiTrackDownloadRoute,
  ApiTrackSearchRoute: ApiTrackSearchRoute,
  ApiTrackViewRoute: ApiTrackViewRoute,
  OgImageDotpngRoute: OgImageDotpngRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  ViewIdRoute: ViewIdRouteWithChildren,
  UnsubscribeIndexRoute: UnsubscribeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
