/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewIdRouteImport } from './routes/view.$id'
import { Route as ViewIdPdfRouteImport } from './routes/view.$id.pdf'
import { Route as ViewIdDownloadRouteImport } from './routes/view.$id.download'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIdRoute = ViewIdRouteImport.update({
  id: '/view/$id',
  path: '/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIdPdfRoute = ViewIdPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => ViewIdRoute,
} as any)
const ViewIdDownloadRoute = ViewIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ViewIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/view/$id': typeof ViewIdRouteWithChildren
  '/view/$id/download': typeof ViewIdDownloadRoute
  '/view/$id/pdf': typeof ViewIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/view/$id': typeof ViewIdRouteWithChildren
  '/view/$id/download': typeof ViewIdDownloadRoute
  '/view/$id/pdf': typeof ViewIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/view/$id': typeof ViewIdRouteWithChildren
  '/view/$id/download': typeof ViewIdDownloadRoute
  '/view/$id/pdf': typeof ViewIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/sitemap.xml'
    | '/view/$id'
    | '/view/$id/download'
    | '/view/$id/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/sitemap.xml'
    | '/view/$id'
    | '/view/$id/download'
    | '/view/$id/pdf'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/sitemap.xml'
    | '/view/$id'
    | '/view/$id/download'
    | '/view/$id/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ArchiveRoute: typeof ArchiveRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ViewIdRoute: typeof ViewIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$id': {
      id: '/view/$id'
      path: '/view/$id'
      fullPath: '/view/$id'
      preLoaderRoute: typeof ViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$id/pdf': {
      id: '/view/$id/pdf'
      path: '/pdf'
      fullPath: '/view/$id/pdf'
      preLoaderRoute: typeof ViewIdPdfRouteImport
      parentRoute: typeof ViewIdRoute
    }
    '/view/$id/download': {
      id: '/view/$id/download'
      path: '/download'
      fullPath: '/view/$id/download'
      preLoaderRoute: typeof ViewIdDownloadRouteImport
      parentRoute: typeof ViewIdRoute
    }
  }
}

interface ViewIdRouteChildren {
  ViewIdDownloadRoute: typeof ViewIdDownloadRoute
  ViewIdPdfRoute: typeof ViewIdPdfRoute
}

const ViewIdRouteChildren: ViewIdRouteChildren = {
  ViewIdDownloadRoute: ViewIdDownloadRoute,
  ViewIdPdfRoute: ViewIdPdfRoute,
}

const ViewIdRouteWithChildren =
  ViewIdRoute._addFileChildren(ViewIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ArchiveRoute: ArchiveRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ViewIdRoute: ViewIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
