/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShortVortsRouteImport } from './routes/short-vorts'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OriginalsRouteImport } from './routes/originals'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as MyTableRouteImport } from './routes/my-table'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AdminAnalyticsRouteImport } from './routes/admin-analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnsubscribeIndexRouteImport } from './routes/unsubscribe.index'
import { Route as ViewIdRouteImport } from './routes/view.$id'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'
import { Route as PublicationSlugRouteImport } from './routes/publication.$slug'
import { Route as OgImageDotpngRouteImport } from './routes/og.image[.]png'
import { Route as ManageTableTokenRouteImport } from './routes/manage-table.$token'
import { Route as ApiTrackViewRouteImport } from './routes/api/track-view'
import { Route as ApiTrackSearchRouteImport } from './routes/api/track-search'
import { Route as ApiTrackDownloadRouteImport } from './routes/api/track-download'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as YomTovSlugYearRouteImport } from './routes/yom-tov.$slug.$year'
import { Route as ViewIdPdfRouteImport } from './routes/view.$id.pdf'
import { Route as ViewIdDownloadRouteImport } from './routes/view.$id.download'
import { Route as ParshaSlugYearRouteImport } from './routes/parsha.$slug.$year'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortVortsRoute = ShortVortsRouteImport.update({
  id: '/short-vorts',
  path: '/short-vorts',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginalsRoute = OriginalsRouteImport.update({
  id: '/originals',
  path: '/originals',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTableRoute = MyTableRouteImport.update({
  id: '/my-table',
  path: '/my-table',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin-analytics',
  path: '/admin-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeIndexRoute = UnsubscribeIndexRouteImport.update({
  id: '/unsubscribe/',
  path: '/unsubscribe/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIdRoute = ViewIdRouteImport.update({
  id: '/view/$id',
  path: '/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationSlugRoute = PublicationSlugRouteImport.update({
  id: '/publication/$slug',
  path: '/publication/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgImageDotpngRoute = OgImageDotpngRouteImport.update({
  id: '/og/image.png',
  path: '/og/image.png',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageTableTokenRoute = ManageTableTokenRouteImport.update({
  id: '/manage-table/$token',
  path: '/manage-table/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackViewRoute = ApiTrackViewRouteImport.update({
  id: '/api/track-view',
  path: '/api/track-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackSearchRoute = ApiTrackSearchRouteImport.update({
  id: '/api/track-search',
  path: '/api/track-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackDownloadRoute = ApiTrackDownloadRouteImport.update({
  id: '/api/track-download',
  path: '/api/track-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const YomTovSlugYearRoute = YomTovSlugYearRouteImport.update({
  id: '/yom-tov/$slug/$year',
  path: '/yom-tov/$slug/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIdPdfRoute = ViewIdPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => ViewIdRoute,
} as any)
const ViewIdDownloadRoute = ViewIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ViewIdRoute,
} as any)
const ParshaSlugYearRoute = ParshaSlugYearRouteImport.update({
  id: '/parsha/$slug/$year',
  path: '/parsha/$slug/$year',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/mission': typeof MissionRoute
  '/my-table': typeof MyTableRoute
  '/offline': typeof OfflineRoute
  '/originals': typeof OriginalsRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/short-vorts': typeof ShortVortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/events': typeof ApiEventsRoute
  '/api/track-download': typeof ApiTrackDownloadRoute
  '/api/track-search': typeof ApiTrackSearchRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/manage-table/$token': typeof ManageTableTokenRoute
  '/og/image.png': typeof OgImageDotpngRoute
  '/publication/$slug': typeof PublicationSlugRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/view/$id': typeof ViewIdRouteWithChildren
  '/unsubscribe/': typeof UnsubscribeIndexRoute
  '/parsha/$slug/$year': typeof ParshaSlugYearRoute
  '/view/$id/download': typeof ViewIdDownloadRoute
  '/view/$id/pdf': typeof ViewIdPdfRoute
  '/yom-tov/$slug/$year': typeof YomTovSlugYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/mission': typeof MissionRoute
  '/my-table': typeof MyTableRoute
  '/offline': typeof OfflineRoute
  '/originals': typeof OriginalsRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/short-vorts': typeof ShortVortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/events': typeof ApiEventsRoute
  '/api/track-download': typeof ApiTrackDownloadRoute
  '/api/track-search': typeof ApiTrackSearchRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/manage-table/$token': typeof ManageTableTokenRoute
  '/og/image.png': typeof OgImageDotpngRoute
  '/publication/$slug': typeof PublicationSlugRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/view/$id': typeof ViewIdRouteWithChildren
  '/unsubscribe': typeof UnsubscribeIndexRoute
  '/parsha/$slug/$year': typeof ParshaSlugYearRoute
  '/view/$id/download': typeof ViewIdDownloadRoute
  '/view/$id/pdf': typeof ViewIdPdfRoute
  '/yom-tov/$slug/$year': typeof YomTovSlugYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/mission': typeof MissionRoute
  '/my-table': typeof MyTableRoute
  '/offline': typeof OfflineRoute
  '/originals': typeof OriginalsRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/short-vorts': typeof ShortVortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/events': typeof ApiEventsRoute
  '/api/track-download': typeof ApiTrackDownloadRoute
  '/api/track-search': typeof ApiTrackSearchRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/manage-table/$token': typeof ManageTableTokenRoute
  '/og/image.png': typeof OgImageDotpngRoute
  '/publication/$slug': typeof PublicationSlugRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/view/$id': typeof ViewIdRouteWithChildren
  '/unsubscribe/': typeof UnsubscribeIndexRoute
  '/parsha/$slug/$year': typeof ParshaSlugYearRoute
  '/view/$id/download': typeof ViewIdDownloadRoute
  '/view/$id/pdf': typeof ViewIdPdfRoute
  '/yom-tov/$slug/$year': typeof YomTovSlugYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-analytics'
    | '/archive'
    | '/contact'
    | '/mission'
    | '/my-table'
    | '/offline'
    | '/originals'
    | '/privacy'
    | '/publications'
    | '/resources'
    | '/robots.txt'
    | '/short-vorts'
    | '/sitemap.xml'
    | '/api/events'
    | '/api/track-download'
    | '/api/track-search'
    | '/api/track-view'
    | '/manage-table/$token'
    | '/og/image.png'
    | '/publication/$slug'
    | '/unsubscribe/$token'
    | '/view/$id'
    | '/unsubscribe/'
    | '/parsha/$slug/$year'
    | '/view/$id/download'
    | '/view/$id/pdf'
    | '/yom-tov/$slug/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-analytics'
    | '/archive'
    | '/contact'
    | '/mission'
    | '/my-table'
    | '/offline'
    | '/originals'
    | '/privacy'
    | '/publications'
    | '/resources'
    | '/robots.txt'
    | '/short-vorts'
    | '/sitemap.xml'
    | '/api/events'
    | '/api/track-download'
    | '/api/track-search'
    | '/api/track-view'
    | '/manage-table/$token'
    | '/og/image.png'
    | '/publication/$slug'
    | '/unsubscribe/$token'
    | '/view/$id'
    | '/unsubscribe'
    | '/parsha/$slug/$year'
    | '/view/$id/download'
    | '/view/$id/pdf'
    | '/yom-tov/$slug/$year'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-analytics'
    | '/archive'
    | '/contact'
    | '/mission'
    | '/my-table'
    | '/offline'
    | '/originals'
    | '/privacy'
    | '/publications'
    | '/resources'
    | '/robots.txt'
    | '/short-vorts'
    | '/sitemap.xml'
    | '/api/events'
    | '/api/track-download'
    | '/api/track-search'
    | '/api/track-view'
    | '/manage-table/$token'
    | '/og/image.png'
    | '/publication/$slug'
    | '/unsubscribe/$token'
    | '/view/$id'
    | '/unsubscribe/'
    | '/parsha/$slug/$year'
    | '/view/$id/download'
    | '/view/$id/pdf'
    | '/yom-tov/$slug/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  ArchiveRoute: typeof ArchiveRoute
  ContactRoute: typeof ContactRoute
  MissionRoute: typeof MissionRoute
  MyTableRoute: typeof MyTableRoute
  OfflineRoute: typeof OfflineRoute
  OriginalsRoute: typeof OriginalsRoute
  PrivacyRoute: typeof PrivacyRoute
  PublicationsRoute: typeof PublicationsRoute
  ResourcesRoute: typeof ResourcesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShortVortsRoute: typeof ShortVortsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiTrackDownloadRoute: typeof ApiTrackDownloadRoute
  ApiTrackSearchRoute: typeof ApiTrackSearchRoute
  ApiTrackViewRoute: typeof ApiTrackViewRoute
  ManageTableTokenRoute: typeof ManageTableTokenRoute
  OgImageDotpngRoute: typeof OgImageDotpngRoute
  PublicationSlugRoute: typeof PublicationSlugRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  ViewIdRoute: typeof ViewIdRouteWithChildren
  UnsubscribeIndexRoute: typeof UnsubscribeIndexRoute
  ParshaSlugYearRoute: typeof ParshaSlugYearRoute
  YomTovSlugYearRoute: typeof YomTovSlugYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-vorts': {
      id: '/short-vorts'
      path: '/short-vorts'
      fullPath: '/short-vorts'
      preLoaderRoute: typeof ShortVortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/originals': {
      id: '/originals'
      path: '/originals'
      fullPath: '/originals'
      preLoaderRoute: typeof OriginalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-table': {
      id: '/my-table'
      path: '/my-table'
      fullPath: '/my-table'
      preLoaderRoute: typeof MyTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-analytics': {
      id: '/admin-analytics'
      path: '/admin-analytics'
      fullPath: '/admin-analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/': {
      id: '/unsubscribe/'
      path: '/unsubscribe'
      fullPath: '/unsubscribe/'
      preLoaderRoute: typeof UnsubscribeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$id': {
      id: '/view/$id'
      path: '/view/$id'
      fullPath: '/view/$id'
      preLoaderRoute: typeof ViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publication/$slug': {
      id: '/publication/$slug'
      path: '/publication/$slug'
      fullPath: '/publication/$slug'
      preLoaderRoute: typeof PublicationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/image.png': {
      id: '/og/image.png'
      path: '/og/image.png'
      fullPath: '/og/image.png'
      preLoaderRoute: typeof OgImageDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-table/$token': {
      id: '/manage-table/$token'
      path: '/manage-table/$token'
      fullPath: '/manage-table/$token'
      preLoaderRoute: typeof ManageTableTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-view': {
      id: '/api/track-view'
      path: '/api/track-view'
      fullPath: '/api/track-view'
      preLoaderRoute: typeof ApiTrackViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-search': {
      id: '/api/track-search'
      path: '/api/track-search'
      fullPath: '/api/track-search'
      preLoaderRoute: typeof ApiTrackSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-download': {
      id: '/api/track-download'
      path: '/api/track-download'
      fullPath: '/api/track-download'
      preLoaderRoute: typeof ApiTrackDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yom-tov/$slug/$year': {
      id: '/yom-tov/$slug/$year'
      path: '/yom-tov/$slug/$year'
      fullPath: '/yom-tov/$slug/$year'
      preLoaderRoute: typeof YomTovSlugYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$id/pdf': {
      id: '/view/$id/pdf'
      path: '/pdf'
      fullPath: '/view/$id/pdf'
      preLoaderRoute: typeof ViewIdPdfRouteImport
      parentRoute: typeof ViewIdRoute
    }
    '/view/$id/download': {
      id: '/view/$id/download'
      path: '/download'
      fullPath: '/view/$id/download'
      preLoaderRoute: typeof ViewIdDownloadRouteImport
      parentRoute: typeof ViewIdRoute
    }
    '/parsha/$slug/$year': {
      id: '/parsha/$slug/$year'
      path: '/parsha/$slug/$year'
      fullPath: '/parsha/$slug/$year'
      preLoaderRoute: typeof ParshaSlugYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ViewIdRouteChildren {
  ViewIdDownloadRoute: typeof ViewIdDownloadRoute
  ViewIdPdfRoute: typeof ViewIdPdfRoute
}

const ViewIdRouteChildren: ViewIdRouteChildren = {
  ViewIdDownloadRoute: ViewIdDownloadRoute,
  ViewIdPdfRoute: ViewIdPdfRoute,
}

const ViewIdRouteWithChildren =
  ViewIdRoute._addFileChildren(ViewIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  ArchiveRoute: ArchiveRoute,
  ContactRoute: ContactRoute,
  MissionRoute: MissionRoute,
  MyTableRoute: MyTableRoute,
  OfflineRoute: OfflineRoute,
  OriginalsRoute: OriginalsRoute,
  PrivacyRoute: PrivacyRoute,
  PublicationsRoute: PublicationsRoute,
  ResourcesRoute: ResourcesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShortVortsRoute: ShortVortsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiTrackDownloadRoute: ApiTrackDownloadRoute,
  ApiTrackSearchRoute: ApiTrackSearchRoute,
  ApiTrackViewRoute: ApiTrackViewRoute,
  ManageTableTokenRoute: ManageTableTokenRoute,
  OgImageDotpngRoute: OgImageDotpngRoute,
  PublicationSlugRoute: PublicationSlugRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  ViewIdRoute: ViewIdRouteWithChildren,
  UnsubscribeIndexRoute: UnsubscribeIndexRoute,
  ParshaSlugYearRoute: ParshaSlugYearRoute,
  YomTovSlugYearRoute: YomTovSlugYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
